BawwaMartApplication/Models/pet.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BawwaMartApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pet()
        {
            this.PetImages = new HashSet<PetImage>();
            this.Sales = new HashSet<Sale>();
        }
    
        public int Id { get; set; }
        public int PetCategoryId { get; set; }
        public string Description { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PetImage> PetImages { get; set; }
        public virtual PetCategory PetCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
    }
}

BawwaMartApplication/Controllers/PetController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BawwaMartApplication.Models;
using Microsoft.AspNet.Identity;

namespace BawwaMartApplication.Controllers
{
    public class PetController : Controller
    {
        private BawwaMartEntities db = new BawwaMartEntities();

        // GET: Pet
        public ActionResult Index()
        {
            List<PetCategory> PetCategoryList = db.PetCategories.ToList();
            ViewBag.PetCategoryList = PetCategoryList;
            return View(db.Pets.ToList());
        }

        public ActionResult Mine()
        {
            String userId = User.Identity.GetUserId();
            return View(db.Pets.Where(x => x.Sales.FirstOrDefault().AspNetUser.Id == userId));
        }

        public ActionResult Search(string Keyword, int PetCategoryId)
        {
            List<PetCategory> PetCategoryList = db.PetCategories.ToList();
            ViewBag.PetCategoryList = PetCategoryList;
            List<Pet> PetList;
            if (Keyword != null && Keyword != "")
            {
                PetList = db.Pets.Where(x => ((x.Description.Contains(Keyword) || x.Sales.FirstOrDefault().Title.Contains(Keyword)) && x.PetCategoryId == PetCategoryId)).ToList();
            }
            else
            {
                PetList = db.Pets.Where(x => x.PetCategoryId == PetCategoryId).ToList();
            }
            return View("Index", PetList);
        }

        // GET: Pet/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pet pet = db.Pets.Find(id);
            if (pet == null)
            {
                return HttpNotFound();
            }
            var PublishedUser = pet.Sales.FirstOrDefault().PublishedUserId;
            User BawwaMartUser = db.Users.Where(x => x.AspNetUserId == PublishedUser).FirstOrDefault();
            ViewBag.FullName = BawwaMartUser.FirstName + " " + BawwaMartUser.LastName;
            ViewBag.Phone = BawwaMartUser.AspNetUser.PhoneNumber;
            ViewBag.Email = BawwaMartUser.AspNetUser.Email;
            return View(pet);
        }

        // GET: Pet/Create
        [Authorize]
        public ActionResult Create()
        {
            List<PetCategory> PetCategoryList = db.PetCategories.ToList();
            ViewBag.PetCategoryList = PetCategoryList;
            return View();
        }

        // POST: Pet/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "PetCategoryId, District, Title, Price, Description, ImageFile1, ImageFile2, ImageFile3")] PetSaleModel petSaleModel)
        {
            Pet pet = new Pet();
            if (ModelState.IsValid)
            {
                pet.CreatedBy = System.Web.HttpContext.Current.User.Identity.Name;
                pet.CreatedDate = DateTime.Now;
                pet.LastModifiedBy = System.Web.HttpContext.Current.User.Identity.Name;
                pet.LastModifiedDate = DateTime.Now;
                pet.Description = petSaleModel.Description;
                pet.PetCategoryId = petSaleModel.PetCategoryId;

                db.Pets.Add(pet);
                db.SaveChanges();

                if (petSaleModel.ImageFile1 != null)
                {
                    SaveImage(petSaleModel.ImageFile1, pet, "1");
                }
                if (petSaleModel.ImageFile2 != null)
                {
                    SaveImage(petSaleModel.ImageFile2, pet, "2");
                }
                if (petSaleModel.ImageFile3 != null)
                {
                    SaveImage(petSaleModel.ImageFile3, pet, "3");
                }

                if (petSaleModel.ImageFile1 == null && petSaleModel.ImageFile2 == null && petSaleModel.ImageFile3 == null)
                {
                    PetImage petImage = new PetImage
                    {
                        ImageUrl = "~/Resources/default.jpg"
                    };

                    petImage.PetId = pet.Id;
                    db.PetImages.Add(petImage);
                    db.SaveChanges();
                }
                Sale sale = new Sale
                {
                    PetId = pet.Id,
                    Price = petSaleModel.Price,
                    Title = petSaleModel.Title,
                    District = petSaleModel.District,
                    LastModifiedDate = DateTime.Now,
                    PublishedUserId = User.Identity.GetUserId()
                };
                db.Sales.Add(sale);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            List<PetCategory> PetCategoryList = db.PetCategories.ToList();
            ViewBag.PetCategoryList = PetCategoryList;
            return View(petSaleModel);
        }

        private void SaveImage(HttpPostedFileBase ImageFile, Pet pet, string fileNameParm)
        {
            string FileName = Path.GetFileNameWithoutExtension(ImageFile.FileName);
            string FileExtension = Path.GetExtension(ImageFile.FileName);
            FileName = FileName.Trim() + "-" + System.Web.HttpContext.Current.User.Identity.Name + "-" + DateTime.Now.ToString("yyyyMMdd") + "-" + fileNameParm + FileExtension;

            PetImage petImage = new PetImage
            {
                ImageUrl = "~/Resources/" + FileName
            };

            string finalImagePath = Path.Combine(Server.MapPath("~/Resources/"), FileName);

            //To copy and save file into server.  
            ImageFile.SaveAs(finalImagePath);

            petImage.PetId = pet.Id;
            db.PetImages.Add(petImage);
            db.SaveChanges();
        }

        // GET: Pet/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            List<PetCategory> petCategoryList = db.PetCategories.ToList();
            ViewBag.petCategoryList = petCategoryList;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pet pet = db.Pets.Find(id);
            if (pet == null)
            {
                return HttpNotFound();
            }

            PetSaleModel petSaleModal = new PetSaleModel();
            petSaleModal.Id = pet.Id;
            petSaleModal.Description = pet.Description;
            petSaleModal.District = pet.Sales.FirstOrDefault().District;
            petSaleModal.PetCategoryId = pet.PetCategoryId;
            petSaleModal.Price = pet.Sales.FirstOrDefault().Price;
            petSaleModal.Title = pet.Sales.FirstOrDefault().Title;
            return View(petSaleModal);
        }

        // POST: Pet/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit([Bind(Include = "Id, PetCategoryId, District, Title, Price, Description")] PetSaleModel petSaleModel)
        {
            Pet pet = db.Pets.Find(petSaleModel.Id);
            pet.LastModifiedDate = DateTime.Now;
            pet.PetCategoryId = petSaleModel.PetCategoryId;
            pet.Description = petSaleModel.Description;
            pet.Sales.FirstOrDefault().District = petSaleModel.District;
            pet.Sales.FirstOrDefault().Title = petSaleModel.Title;
            pet.Sales.FirstOrDefault().Price = petSaleModel.Price;

            pet.LastModifiedBy = System.Web.HttpContext.Current.User.Identity.Name;
            pet.LastModifiedDate = DateTime.Now;
            if (ModelState.IsValid)
            {
                db.Entry(pet).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(petSaleModel);
        }

        // GET: Pet/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pet pet = db.Pets.Find(id);
            if (pet == null)
            {
                return HttpNotFound();
            }
            return View(pet);
        }

        // POST: Pet/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteConfirmed(int id)
        {
            List<PetImage> PetImageList = db.PetImages.Where(x => x.PetId == id).ToList();
            foreach (PetImage petImage in PetImageList)
            {
                db.PetImages.Remove(petImage);
            }

            List<Sale> SaleList = db.Sales.Where(x => x.PetId == id).ToList();
            foreach (Sale sale in SaleList)
            {
                db.Sales.Remove(sale);
            }

            Pet pet = db.Pets.Find(id);
            db.Pets.Remove(pet);

            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BawwaMartApplication/Views/Pet/Create.cshtml
@model BawwaMartApplication.Models.PetSaleModel

@{
    ViewBag.Title = "Create";
}

<h2>Pet</h2>


@using (Html.BeginForm("Create", "Pet", FormMethod.Post, new { enctype="multipart/form-data"})) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.Label("Pet Category", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.PetCategoryId, new SelectList(ViewBag.PetCategoryList, "Id", "Name"), new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.PetCategoryId, "", new { @class = "text-danger" })
        </div>
    </div>

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.Label("Title", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.Label("District", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.District, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.District, "", new { @class = "text-danger" })
        </div>
    </div>


    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.Label("Price", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", @type = "number", @min = "0", @step = "0.01", @value = "0" } })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Description", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Description, 10, 100, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Image", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="ImageFile1" class="form-control" />
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Image", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="ImageFile2" class="form-control" />
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Image", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="ImageFile3" class="form-control" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-success" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BawwaMartApplication/Views/Pet/Delete.cshtml
@model BawwaMartApplication.Models.Pet

@{
    ViewBag.Title = "Delete";
}

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Pet Category")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PetCategory.Name)
        </dd>

        <dt>
            @Html.DisplayName(" Title")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sales.FirstOrDefault().Title)
        </dd>

        <dt>
            @Html.DisplayName(" Description")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>


        <hr />

        <dt>
            @Html.DisplayName("Created By")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

        <dt>
            @Html.DisplayName("Created Date")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayName("Modified By")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastModifiedBy)
        </dd>

        <dt>
            @Html.DisplayName("Modified Date")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastModifiedDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BawwaMartApplication/Views/Pet/Details.cshtml
@model BawwaMartApplication.Models.Pet

@{
    ViewBag.Title = "Details";
}

<h2>@Html.DisplayFor(model => model.Sales.FirstOrDefault().Title)</h2>

<div>
    @if (User.Identity.Name != Model.Sales.FirstOrDefault().AspNetUser.Email)
    {
        <input type="button" class="btn btn-warning" value="Contact Seller" data-toggle="modal" data-target="#sellerModal" />

        if (Request.IsAuthenticated && User.IsInRole("Admin"))
        {
            @Html.ActionLink("Delete", "Delete", new { id = Model.Id }, new { @class = "btn btn-danger" })
        }
    }
    else
    {
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "btn btn-primary" }) <span>|</span> 
        @Html.ActionLink("Delete", "Delete", new { id = Model.Id }, new { @class = "btn btn-danger" })
    }
    <hr />
    <dl class="dl-horizontal">
        <dt>

        </dt>

        <dd>
            @foreach (var petImage in Model.PetImages)
            {
                <img src="@Url.Content(petImage.ImageUrl)" alt="Image" height="100" width="100" />
            }
        </dd>
        <hr />
        <dt>
            @Html.DisplayName("Title")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sales.FirstOrDefault().Title)
        </dd>

        <dt>
            @Html.DisplayName("Pet Category")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PetCategory.Name)
        </dd>

        <dt>
            @Html.DisplayName(" Description")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayName("Price")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sales.FirstOrDefault().Price)
        </dd>

        <dt>
            @Html.DisplayName("District")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sales.FirstOrDefault().District)
        </dd>

        <hr />
        <dt>
            @Html.DisplayName("Created Date")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayName("Modified Date")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastModifiedDate)
        </dd>

    </dl>
</div>
<!-- Modal -->
<div class="modal fade" id="sellerModal" tabindex="-1" role="dialog" aria-labelledby="sellerModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title" id="sellerModalLabel">Seller Info</h2>

            </div>
            <div class="modal-body">
                <div>
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayName("Full Name")
                        </dt>

                        <dd>
                            @ViewBag.FullName
                        </dd>
                        <dt>
                            @Html.DisplayName("Mobile")
                        </dt>
                        <dd>
                            @ViewBag.Phone
                        </dd>
                        <dt>
                            @Html.DisplayName("Email")
                        </dt>
                        <dd>
                            @ViewBag.Email
                        </dd>
                    </dl>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<p>
    @if (User.Identity.Name == Model.Sales.FirstOrDefault().AspNetUser.Email)
    {
        
    }

    @Html.ActionLink("Back to List", "Index")
</p>

BawwaMartApplication/Views/Pet/Edit.cshtml
@model BawwaMartApplication.Models.PetSaleModel

@{
    ViewBag.Title = "Edit";
}

<h2>@Model.Title</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.Label("Pet Category", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.PetCategoryId, new SelectList(ViewBag.petCategoryList, "Id", "Name"), new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PetCategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Title", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("District", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.District, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.District, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.Label("Price", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", @type = "number", @min = "0", @step = "0.01", @value = "0" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Description", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, 10, 100, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BawwaMartApplication/Views/Pet/Index.cshtml
@model IEnumerable<BawwaMartApplication.Models.Pet>

@{
    ViewBag.Title = "Index";
}

<h2>Find your Pet</h2>

<form class="pet-search-form" id="myForm" action="/Pet/Search" method="Post">
    <div class="form-row">
        <div class="col-md-2">
            @Html.DropDownList("PetCategoryId", new SelectList(ViewBag.PetCategoryList, "id", "name"), new { @class = "form-control" })
        </div>
        <div class="col-md-2">
            <input type="text" name="Keyword" class="form-control" placeholder="Keyword">
        </div>
        <div class="col-md-2">
            <input type="submit" value="Search" class="btn btn-primary" />
        </div>
    </div>
</form>



<table class="table pet-table">
    <tr>
        <th></th>
        <th>
            @Html.DisplayName("Title")
        </th>
        <th>
            @Html.DisplayName("Price")
        </th>
        <th>
            @Html.DisplayName("Category")
        </th>
        <th>
            @Html.DisplayName("Description")
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                <img src="@Url.Content(item.PetImages.FirstOrDefault().ImageUrl)" alt="Image" height="100" width="100" class="img-thumbnail" />
            </td>
            <td>
                <p>@Html.ActionLink(@item.Sales.FirstOrDefault().Title, "Details", "Pet", new { id = item.Id }, null)</p>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sales.FirstOrDefault().Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PetCategory.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
        </tr>
    }

</table>

BawwaMartApplication/Views/Pet/Mine.cshtml
@model IEnumerable<BawwaMartApplication.Models.Pet>

@{
    ViewBag.Title = "Mine";
}

<h2>Your Adds</h2>

<table class="table">
    <tr>
        <th></th>
        <th>
            @Html.DisplayName("Title")
        </th>
        <th>
            @Html.DisplayName("Price")
        </th>
        <th>
            @Html.DisplayName("Category")
        </th>
        <th>
            @Html.DisplayName("Description")
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                <img src="@Url.Content(item.PetImages.FirstOrDefault().ImageUrl)" alt="Image" height="100" width="100"  class="img-thumbnail"  />
            </td>
            <td>
                <p>@Html.ActionLink(@item.Sales.FirstOrDefault().Title, "Details", "Pet", new { id = item.Id }, null)</p>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sales.FirstOrDefault().Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PetCategory.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
        </tr>
    }

</table>